install.packages("devtools")
renv::snapshot()
usethis::git_vaccinate()
usethis::git_sitrep()
usethis::use_description(check_name = FALSE)
install.packages("rmarkdown")
usethis::use_readme_rmd()
usethis::use_lifecycle_badge("experimental")
devtools::session_info()
usethis::edit_r_profile()
renv::snapshot()
roxygen2::roxygenise()
